# Generated by Django 4.2.5 on 2023-10-02 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_post_likes_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
