# Generated by Django 4.2.5 on 2023-10-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_body_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body_comment',
            field=models.CharField(max_length=250),
        ),
    ]
