# Generated by Django 4.2.5 on 2023-10-04 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_alter_comment_body_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['publish_comment']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_publish_b65f33_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['publish_comment'], name='blog_commen_publish_1a2185_idx'),
        ),
    ]
